language: go

os:
  - linux

go_import_path: github.com/wamuir/matrix-market

go:
  - 1.15.x
  - 1.16.x
  - tip

before_install:
  - go get -u github.com/james-bowman/sparse
  - go get -u gonum.org/v1/gonum/mat

script:
   - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
   - bash <(curl -s https://codecov.io/bash) 
